baseURL = "https://foolwei-code.github.io/"
languageCode = 'zh-cn'
title = "Konger's blog"
theme = 'github-style'
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = 'Konger'
  description = 'In solitude, where we are least alone.'
  github = 'foolwei-code'
  email = '3288529254@qq.com'
  url = 'https://foolwei.com/'
  keywords = 'blog, google analytics'
  rss = true
  lastmod = true
  avatar = '/images/avatar.png'
  headerIcon = "/images/page.png"
  location = 'China'
  enableGitalk = true
  custom_css = ["css/custom.css"]
  custom_js = ["js/custom.js"]
  enableSearch = true

[outputs]
  home = ["html", "json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false

[caches]
 [caches.images]
  dir = ':cacheDir/images'

lastmod = true

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

enableGitalk = true

[params.gitalk]
  clientID = "Ov23lizw2fjqfY43cIRI"
  clientSecret = "b3f538832e3306c84cd3dd5aa1275c4bb8488120"
  repo = "foolwei-code.github.io"
  owner = "foolwei-code"
  admin = "foolwei-code"
  id = "location.pathname"
  labels = "gitalk"
  perPage = 30
  pagerDirection = "last"
  createIssueManually = true
  distractionFreeMode = false
